### ISSUE TITLE
Buchung von Positionen - Dropdown Menü von Größen enthält falsche Werte

### ISSUE THREAD

**Issue by Binder-F** [argh87/de.hs-fulda.et.it.project#31]
Wenn man eine Buchung vornehmen will und eine Kategorie auswählt, danach bemerkt das man eine andere Kategorie haben will. Stehen im Auswahl Feld "Größen" die Werte der zuerst gewählten Kategorie + die neuen Größen der aktuell gewählten Kategorie.

**Comment by WiederT** [comment]
Servus @Binder-F . Ich wollte dir nur mal den aktuellen Stand geben: Ich bin aufgrund der Hausarbeit, wo wir eure Umfrage für brauchten leider noch nicht dazu gekommen mich darum zu kümmern, werde das aber morgen oder spätestens übermorgen tun. Vielen Dank für dein Testen und fühl dich frei weitere Bugs aufzunehmen ;-) 

Beste Grüße,
Tim
